<?php
namespace App\Calc;

class Calc extends CalcService
{
    public $num1;
    public $num2;

    public function __construct(float $one, float $two){
        $this->num1 = $one;
        $this->num2 = $two;
    }
    public static function calculator($calc, string $operator)
    {
        return parent::calculator($calc, $operator); // TODO: Change the autogenerated stub
    }
}